# Generated by Django 3.2.6 on 2021-10-24 08:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('mL', 'millilitres'), ('kg', 'kilograms'), ('dozen', 'dozen'), ('L', 'litres'), ('g', 'grams')], default='kg', max_length=5)),
                ('category', models.CharField(choices=[('F', 'Fruit'), ('O', 'Other'), ('L', 'Legumes and Nuts'), ('E', 'Eggs'), ('D', 'Dairy'), ('V', 'Vegetables'), ('H', 'Herbs'), ('M', 'Meat')], default='O', max_length=1)),
                ('quality', models.CharField(choices=[('C', 'C'), ('A+', 'A+'), ('B', 'B'), ('U', 'Unrated'), ('A', 'A')], default='U', max_length=2)),
                ('img_url', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-1, 'Cancelled'), (3, 'Delivered'), (0, 'Placed'), (1, 'Confirmed by seller'), (2, 'In transit')], default=0)),
                ('buyer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 18, 2, 11, 47018))),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('orders', models.ManyToManyField(to='core.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('items', models.ManyToManyField(blank=True, to='core.OrderItem')),
            ],
        ),
    ]
