# Generated by Django 3.2.6 on 2021-10-24 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'Legumes and Nuts'), ('E', 'Eggs'), ('F', 'Fruit'), ('V', 'Vegetables'), ('M', 'Meat'), ('D', 'Dairy'), ('H', 'Herbs'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('U', 'Unrated'), ('B', 'B'), ('C', 'C')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('dozen', 'dozen'), ('L', 'litres'), ('kg', 'kilograms'), ('g', 'grams'), ('mL', 'millilitres')], default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'In transit'), (3, 'Delivered'), (0, 'Placed'), (-1, 'Cancelled'), (1, 'Confirmed by seller')], default=0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='last_viewed',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 18, 24, 32, 608409)),
        ),
    ]
