# Generated by Django 3.2.6 on 2021-10-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211024_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'Meat'), ('D', 'Dairy'), ('E', 'Eggs'), ('L', 'Legumes and Nuts'), ('V', 'Vegetables'), ('H', 'Herbs'), ('F', 'Fruit')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('A+', 'A+'), ('U', 'Unrated'), ('C', 'C')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('L', 'litres'), ('dozen', 'dozen'), ('mL', 'millilitres'), ('g', 'grams')], default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed by seller'), (3, 'Delivered'), (2, 'In transit'), (-1, 'Cancelled'), (0, 'Placed')], default=0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='last_viewed',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 18, 39, 28, 309316)),
        ),
    ]
